### ISSUE TITLE
Add to Bower?

### ISSUE THREAD

**Issue by alexbndk** [jsdf/react-form-for#1]
Would you be willing to add this library to Bower?

I'm using this in a Rails app and it works great! Only problem is that, since I'm using just vanilla Sprockets, I had to compile a custom bundle that I could drop in vendor. It would be much more convenient if it were available on Bower and hence through [Rails Assets](https://rails-assets.org).

Thanks.

**Comment by jsdf** [comment]
`react-form-for` is now available on Bower. The Bower package provides a UMD bundle which will expose `ReactFormFor` (assuming you're not using RequireJS, which I haven't tested). It requires `React` (addons build) to be globally available on `window` (or via RequireJS I guess).

**Comment by alexbndk** [comment]
Thanks a lot! I got it installed but it looks like React is getting included in the compiled version though.

**Comment by jsdf** [comment]
Whoops. Try version 1.0.3

**Comment by alexbndk** [comment]
Yep, the compiled version is correct now, although I think you still need to bump the bower.json version.

**Comment by jsdf** [comment]
Should be good now. Had to automate updating npm and bower versions in sync

**Comment by alexbndk** [comment]
All good now. Thanks again.
